---
title: "SentimentAnalysis"
author: "Michael Ian Leguira"
date: '2022-06-19'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, loading libraries, echo=FALSE, warning=FALSE, results='hide', message=FALSE}
library (twitteR)

library(tm)
library(ggplot2)
library (stringr)

library (syuzhet)
library(wordcloud)
library (RColorBrewer)
library(tinytex)

```


```{r, Setting_Credentials, results='hide', echo=FALSE, message=FALSE}
#set the credentials
Consumer_secret <- "ZdGZi9aGG0VbOj1cdWXk6PzgQzmpAq7s3z9LsLUby2vGV7iHD7"
Consumer_key <- "ll18xpJcySQHXceY9oXO1cuZZ"
Access_secret <- "7EXHyEA844xyeCNfWgMd5ffoZGjfaWMmw1jw92VFSKAVN"
Access_token <- "1533805509161017345-nT2JxCrqKUIplJXSrrdXDRoyG5grER"
```

##Introduction
Sentiment Analysis towards the account of Resident_bio

```{r, extracting twitter, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#extract timeline tweets
extractTimelineTweets <- function (username, tweetCount){
  #timeline tweets
  twitterUser <- getUser(username)
  tweets = userTimeline(twitterUser, n=tweetCount)
  tweets.df = twListToDF(tweets)
  tweets.df$text <- sapply (tweets.df$text, function(x) iconv(enc2utf8(x), sub = "byte"))
  
  return (tweets.df)
}

encodeSentiment <- function(x) {
  if(x <= -0.5){
    "1) very negative"
  }else if(x > -0.5 & x < 0){
    "2) negative"
  }else if(x > 0 & x < 0.5){
    "4) positive"
  }else if(x >= 0.5){
    "5) very positive"
  }else {
    "3) neutral"
  }
}


```


```{r, connect to twitter app, results='hide', echo=FALSE, message=FALSE}

#connect to twitter app
setup_twitter_oauth(consumer_key = Consumer_key,
                    consumer_secret = Consumer_secret,
                    access_token = Access_token,
                    access_secret = Access_secret
                    )

tweetsDF <- extractTimelineTweets ("Resident_bio", 3200)


```


```{r, cleaning data, echo=FALSE, warning=FALSE}
nohandles <- str_replace_all(tweetsDF$text, "@\\w+", " ")
nohandles$cleanedText <- gsub("http.*", " ", nohandles)
nohandles$cleanedText <- gsub("https.*", " ", nohandles$cleanedText )


nohandles$cleanedText <- str_replace_all(nohandles$cleanedText, "[^[:alnum:]]", " ")
nohandles$cleanedText <-  str_replace_all(nohandles$cleanedText,"[[^a-zA-Z0-9]]", " ")
head(nohandles$cleanedText)



```

##Wordcloud

```{r, wordcloudd, echo=FALSE, results='hide', warning=FALSE}
wordCorpus <- Corpus(VectorSource(nohandles$cleanedText))
wordCorpus[[1]]$content

#removing punctuations
wordCorpus <- tm_map(wordCorpus, removePunctuation)
wordCorpus[[1]]$content
wordCorpus <- tm_map(wordCorpus, removeNumbers)
wordCorpus <- tm_map(wordCorpus, content_transformer(tolower))
wordCorpus[[1]]$content
wordCorpus <- tm_map(wordCorpus, removeWords, stopwords("english"))
wordCorpus[[1]]$content
wordCorpus <- tm_map(wordCorpus, removeWords, c("amp"))
wordCorpus <- tm_map(wordCorpus, removeWords, c("ste"))#manual assignment
wordCorpus[[5]]$content
wordCorpus <- tm_map(wordCorpus, stripWhitespace)
wordCorpus[[1]]$content
str(wordCorpus)

pal <- brewer.pal(9,"YlGnBu")
pal <- pal[-(1:4)]
set.seed(123)
par(mfrow = c(1,1))
wordcloud(words = wordCorpus, scale=c(5,0.1), max.words=500, random.order=FALSE, 
          rot.per=0.35, use.r.layout=FALSE, colors=pal)



```

```{r, sentiment analysis_part1, warning=FALSE, echo=FALSE, results='hide', message=FALSE}
#sentiment analysis
tweetSentiments <- get_sentiment (tweetsDF$text,method = "syuzhet")
tweets <- cbind(tweetsDF, tweetSentiments)

#positive and negative sentiments
tweets$sentiment <- sapply(tweets$tweetSentiments,encodeSentiment)
head(tweets, n = 1)


qplot(tweets$tweetSentiments) + theme(legend.position="none")+
  xlab("Sentiment Score") +
  ylab("Number of tweets") + 
  ggtitle("Tweets by Sentiment Score") 


```


```{r, sentiment analysis_part2, echo=FALSE}
ggplot(tweets, aes(sentiment, fill = sentiment)) +
  geom_bar() + 
  theme(legend.position="none", axis.title.x = element_blank()) +
  ylab("Number of tweets") + 
  ggtitle("Tweets by Sentiment") 


```


```{r, sentiment analysis_part3, echo=FALSE}
tweetSentiments <- get_nrc_sentiment(tweetsDF$text)
tweets <- cbind(tweetsDF, tweetSentiments)

sentimentTotals <- data.frame(colSums(tweets[,c(17:26)]))

names(sentimentTotals) <- "count"
sentimentTotals <- cbind("sentiment" = rownames(sentimentTotals), sentimentTotals)
rownames(sentimentTotals) <- NULL
sentimentTotals

```


```{r, sentiment analysis_final_ploting,echo=FALSE}
ggplot(data = sentimentTotals, aes(x = sentiment, y = count)) +
  geom_bar(aes(fill = sentiment), stat = "identity") +
  theme(legend.position = "none") +
  xlab("Sentiment") + ylab("Total Count") + ggtitle("Total Sentiment Score for All Tweets")



```

##Conclusion
I've hide all the warning,messages,results and source code so that my visual pdf plot is much more cleaner you can still check the code in source file
